/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-02-28 20:25:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"index.css\">\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("  href=\"https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <a href=\"#\" class=\"logo\"><img src=\"img/bx-cycling.svg\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"bx bx-menu\" id=\"menu-icon\"></div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"navbar\">\r\n");
      out.write("            <li><a href=\"#home\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#ride\">Ride</a></li>\r\n");
      out.write("            <li><a href=\"#services\">Services</a></li>\r\n");
      out.write("            <li><a href=\"#about\">About</a></li>\r\n");
      out.write("            <li><a href=\"#reviews\">Reviews</a></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"header-btn\">\r\n");
      out.write("            <!-- <button onclick=\"document.getElementById('id01').style.display='block'\" style=\"width:auto;\">Sign Up</button> -->\r\n");
      out.write("            <button  type=\"button\" class=\"sign\" style=\"width:auto;\"><a href=\"loginn.jsp\"  style=\"color:white;\">Sing up</a></button>\r\n");
      out.write("            <button class=\"sign-in\" onclick=\"document.getElementById('id01').style.display='block'\" style=\"width:auto;\"> \r\n");
      out.write("            <a href=\"registration.jsp\" style=\"color:white;\">Sing In</a></button>\r\n");
      out.write("\r\n");
      out.write("            <!-- <a href=\"onclick=\" class=\"sign\" onclick=\"document.getElementById('id01');\">Sign Up</a> -->\r\n");
      out.write("            <!-- <a href=\"#\" class=\"sign-in\">Sign In</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"home\" id=\"home\">\r\n");
      out.write("        <div class=\"text\">\r\n");
      out.write("            <h1><span>Looking </span>to <br>rent a Bike</h1>\r\n");
      out.write("            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo, rerum nam?</p>\r\n");
      out.write("            <div class=\"app-stores\">\r\n");
      out.write("                <img src=\"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_108/play_ip0jfp\" alt=\"\">\r\n");
      out.write("                <img src=\"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_108/iOS_ajgrty\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-container\">\r\n");
      out.write("            <form action=\"\">\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span>Location</span>\r\n");
      out.write("                    <input type=\"search\" name=\"\" id=\"\" placeholder=\"Search Places\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\"><span>Pick-Up Date</span>\r\n");
      out.write("                <input type=\"date\" name=\"\" id=\"\"></div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-box\"><span>Return Date</span>\r\n");
      out.write("                    <input type=\"date\" name=\"\" id=\"\"></div>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"submit\" name=\"\" id=\"\" class=\"btn\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"ride\" id=\"ride\">\r\n");
      out.write("        <div class=\"heading\">\r\n");
      out.write("            <span>How Its Work</span>\r\n");
      out.write("            <h1>Rent with 3 Easy Steps</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"ride-container\">\r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <i class=\"bx bxs-map\"></i>\r\n");
      out.write("                <h2>Choose a location </h2>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. \r\n");
      out.write("                    Doloribus reiciendis et est, cum officiis voluptate.</p>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <i class=\"bx bxs-calendar-check\"></i>\r\n");
      out.write("                <h2>Pick-Up Date </h2>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. \r\n");
      out.write("                    Doloribus reiciendis et est, cum officiis voluptate.</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <i class=\"bx bxs-calendar-star\"></i>\r\n");
      out.write("                <h2>Book A Bike </h2>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. \r\n");
      out.write("                    Doloribus reiciendis et est, cum officiis voluptate.</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Services -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"services\" id=\"services\">\r\n");
      out.write("        <div class=\"heading\">\r\n");
      out.write("            <span>Best Services</span>\r\n");
      out.write("\r\n");
      out.write("            <h1>Explore Out Top Deals <br>From Top Rated Dealers</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("            <div class=\"services-container\">\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"box-img\"><img src=\"img/bike1.jpg\" alt=\"\"></div>\r\n");
      out.write("                    <p>2017</p>\r\n");
      out.write("                    <h3>2018 Lorem, ipsum.</h3>\r\n");
      out.write("                    <h2>200rs | 350rs <span>/Hour</span></h2>\r\n");
      out.write("                    <a href=\"#\" class=\"btn\">Rent Now</a>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"box-img\"><img src=\"img/bike2.jpg\" alt=\"\"></div>\r\n");
      out.write("                    <p>2017</p>\r\n");
      out.write("                    <h3>2018 Lorem, ipsum.</h3>\r\n");
      out.write("                    <h2>200rs | 350rs <span>/Hour</span></h2>\r\n");
      out.write("                    <a href=\"#\" class=\"btn\">Rent Now</a>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"box-img\"><img src=\"img/bike3.jpg\" alt=\"\"></div>\r\n");
      out.write("                    <p>2017</p>\r\n");
      out.write("                    <h3>2018 Lorem, ipsum.</h3>\r\n");
      out.write("                    <h2>200rs | 350rs <span>/Hour</span></h2>\r\n");
      out.write("                    <a href=\"#\" class=\"btn\">Rent Now</a>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"box-img\"><img src=\"img/bike4.jpg\" alt=\"\"></div>\r\n");
      out.write("                    <p>2017</p>\r\n");
      out.write("                    <h3>2018 Lorem, ipsum.</h3>\r\n");
      out.write("                    <h2>200rs | 350rs <span>/Hour</span></h2>\r\n");
      out.write("                    <a href=\"#\" class=\"btn\">Rent Now</a>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"box-img\"><img src=\"img/bike5.jpg\" alt=\"\"></div>\r\n");
      out.write("                    <p>2017</p>\r\n");
      out.write("                    <h3>2018 Lorem, ipsum.</h3>\r\n");
      out.write("                    <h2>200rs | 350rs <span>/Hour</span></h2>\r\n");
      out.write("                    <a href=\"#\" class=\"btn\">Rent Now</a>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"box-img\"><img src=\"img/bike6.jpg\" alt=\"\"></div>\r\n");
      out.write("                    <p>2017</p>\r\n");
      out.write("                    <h3>2018 Lorem, ipsum.</h3>\r\n");
      out.write("                    <h2>200rs | 350rs <span>/Hour</span></h2>\r\n");
      out.write("                    <a href=\"#\" class=\"btn\">Rent Now</a>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ABOUT -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"about\" id=\"about\">\r\n");
      out.write("        <div class=\"heading\">\r\n");
      out.write("            <span>About Us</span>\r\n");
      out.write("            <h1>Best Customer Experience </h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"about-container\">\r\n");
      out.write("            <div class=\"about-img\">\r\n");
      out.write("                <img src=\"img/bikeonrent.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"about-text\">\r\n");
      out.write("                <span>About Us</span>\r\n");
      out.write("                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nostrum illo, recusandae autem eius quas quam quos placeat suscipit laboriosam odio ea voluptatibus cum enim debitis! Mollitia optio fugiat asperiores! Velit quam eligendi laudantium asperiores.</p>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur iste est vel facilis dolorem voluptatibus, mollitia incidunt sed.</p>\r\n");
      out.write("                <a href=\"#\" class=\"btn\">Learn More</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Reviews -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"reviews\" id=\"reviews\">\r\n");
      out.write("        <div class=\"heading\">\r\n");
      out.write("            <span>Reviews</span>\r\n");
      out.write("            <h1>Whats Our Customer Say</h1>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"reviews-container\">\r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <div class=\"rev-img\">\r\n");
      out.write("                    <img src=\"img/face1.jpg\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Someone Name</h2>\r\n");
      out.write("                <div class=\"stars\">\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star-half\"></i>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores praesentium minima laboriosam architecto tempore tempora aliquam iusto quaerat.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <div class=\"rev-img\">\r\n");
      out.write("                    <img src=\"img/face2.jpg\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Someone Name</h2>\r\n");
      out.write("                <div class=\"stars\">\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star-half\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi libero quam aut ex sit iure explicabo magni vitae?</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <div class=\"rev-img\">\r\n");
      out.write("                    <img src=\"img/face3.jpg\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Someone Name</h2>\r\n");
      out.write("                <div class=\"stars\">\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star\"></i>\r\n");
      out.write("                    <i class=\"bx bxs-star-half\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia magni tempora qui sit iusto nostrum dolor reprehenderit quisquam.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- newsletter -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"newsletter\">\r\n");
      out.write("        <h2>Subscribe To Newsletter</h2>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <input type=\"text\" name=\"\" id=\"\" placeholder=\"Enter Your Email....\">\r\n");
      out.write("            <a href=\"#\" class=\"btn\">Subscribe</a>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"copyright\">\r\n");
      out.write("        <p>&#169; AbdulKhadar All Right Reserved</p>\r\n");
      out.write("        <div class=\"social\">\r\n");
      out.write("            <a href=\"#\"><i class=\"bx bxl-facebook\"></i></a>\r\n");
      out.write("            <a href=\"https://x.com/AbdulkPatel?t=AuCAkdmhdkHO495NP4v4IA&s=09\" target=\"_blank\"><i class=\"bx bxl-twitter\"></i></a>\r\n");
      out.write("            <a href=\"https://instagram.com/abd_ul_khadar?igshid=YTQwZjQ0NmI0OA==\" target=\"_blank\"><i class=\"bx bxl-instagram\"></i></a>\r\n");
      out.write("            <a href=\"https://github.com/Abdulk-P\" target=\"_blank\"><i class=\"bx bxl-github\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- login form -->\r\n");
      out.write("\r\n");
      out.write("   <!-- <!--  <h2>Modal Signup Form</h2>\r\n");
      out.write("<button onclick=\"document.getElementById('id01').style.display='block'\" style=\"width:auto;\">Sign Up</button> --> \r\n");
      out.write("    \r\n");
      out.write("<div id=\"id01\" class=\"modal\">\r\n");
      out.write("  <span onclick=\"document.getElementById('id01').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\r\n");
      out.write("  <form class=\"modal-content\" action=\"/action_page.php\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h1>Sign Up</h1>\r\n");
      out.write("      <p>Please fill in this form to create an account.</p>\r\n");
      out.write("      <hr>\r\n");
      out.write("      <label for=\"email\"><b>Email</b></label>\r\n");
      out.write("      <input type=\"text\" placeholder=\"Enter Email\" name=\"email\" required>\r\n");
      out.write("    \r\n");
      out.write("      <label for=\"psw\"><b>Password</b></label>\r\n");
      out.write("      <input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" required>\r\n");
      out.write("    \r\n");
      out.write("      <label for=\"psw-repeat\"><b>Repeat Password</b></label>\r\n");
      out.write("      <input type=\"password\" placeholder=\"Repeat Password\" name=\"psw-repeat\" required>\r\n");
      out.write("      \r\n");
      out.write("      <label>\r\n");
      out.write("        <input type=\"checkbox\" checked=\"checked\" name=\"remember\" style=\"margin-bottom:15px\"> Remember me\r\n");
      out.write("      </label>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <div class=\"clearfix\">\r\n");
      out.write("        <button type=\"button\" onclick=\"document.getElementById('id01').style.display='none'\" class=\"cancelbtn\">Cancel</button>\r\n");
      out.write("        <button type=\"submit\" class=\"signupbtn\">Sign Up</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://unpkg.com/scrollreveal\"></script>\r\n");
      out.write("    <script src=\"main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Get the modal\r\n");
      out.write("        var modal = document.getElementById('id01');\r\n");
      out.write("        \r\n");
      out.write("        // When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("        window.onclick = function(event) {\r\n");
      out.write("          if (event.target == modal) {\r\n");
      out.write("            modal.style.display = \"none\";\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("        </script>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
